Add synced dumping for database
Considering the incapable implementation from the official API by
PickleDB which causes the following exception:

    RuntimeError: can't create new thread at interpreter shutdown

Add my own implementation version of database's dumping to keep the
operation synchorized to the current thread to get rid of the exception
mentioned above.

Signed-off-by: src_resources <src.res.211@gmail.com>